[package]
name = "try-runtime-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Substrate's programmatic testing framework for power users."

[[bin]]
name = "try-runtime-cli"
path = "main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
try-runtime-core = { path = "../core", features = ["cli"] }

clap = { version = "4.0.9", features = ["derive"] }
env_logger = "0.10.0"
parity-scale-codec = { version = "3.6.1", features = ["derive"] }
tokio = { version = "1.25.0", features = ["full"] }

# Substrate
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
node-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
node-primitives = { git = "https://github.com/paritytech/substrate", branch = "master" }
