name: Rust Docs to GitHub Pages

on:
  push:
    branches:
      - liam-v0.1.0

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.6.1"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add wasm32-unknwon-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
