name: Rust tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rust-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.6.1"

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Build binary for test
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
